env:
  global:
  - GH_REF: git.duapp.com/appidenoe6p61ew/
  - secure: g92iYrAt+xs6NFRCjxAW1mTEilnvL9yls9AwmExdQJz/Hc1YUHL5THZVL7dyWqjtP18HtZPOLbdgLCS5+K76OPFthfbZQMGNPUzdzzQdI4P7+i3uKzU7Lm71Ul23fUs3txuvp9Fprv5+OtiMUFzRlhLIfrnX35uAJShn3auMpkE=
  - secure: Q0czucyN1t6RQrKPWznTyOrMvFWNhiu5N8gwta0BAJJuQH2+1WUi4vgPqw1GZhOVCpIqg0PWogFiSoDHheIt+zMCsC9P0uVUf7k1jJI/O647PpP9sJ0TmhIQfMk9UhXT9NQF6QYUn94j2yOVz94MGVPogMeCE7EpC6lZnlZLyt8=
language: ruby
rvm:
- 2.1.7
script:
- sh build.sh
after_script:
- sh -x pub.sh|grep -v "${GIT_TOKEN}"
