name: 百度 FEX 团队
url: http://fex.baidu.com
source:      .
destination: ./_site
lsi:      false
safe:     false
markdown: kramdown
permalink: /blog/:year/:month/:title/
paginate: 12
paginate_path: "articles/page:num"
encoding: utf-8
gems: [jekyll-paginate] 
post_defaults:
  layout: post

#redcarpet:
#  extensions: ["tables", "autolink"]

